docs/flow_chart.drawio.svg
=> make_re flow_chart #1

.github/workflows/test.yml, Makefile, include/exec.h, include/minishell.h, include/minishell_type.h, include/parse.h, src/exec/exec.c, src/minishell.c, src/parse/parse.c
=> add ci/cd test workflow!

include/minishell.h, include/minishell_type.h
어제 정의를 했던 type들에 대해서 header 파일로 정의 해보았습니다!
issues: #6
=> add typedef header file

Makefile, include/exec.h, include/minishell.h, include/minishell_type.h, include/parse.h, src/exec/exec.c, src/minishell.c, src/parse/parse.c
아래의 prototype를 기준으로 프로젝트를 초기 설정을 해보았습니다.
```c
t_AST	*parse_cmd(char *cmd);
int		exec_cmd(t_AST *cmds);
```
issues: #7
=> setup prototype

src/minishell.c
make init_envp function
envp 크기 +1 만큼 env에 할당 후 옮겨준다
=> make init_envp function

include/exec.h, src/exec/exec.c, src/minishell.c
exec_cmd함수에서 부족한 인자를 추가 #11 
init_envp의 동작 일부 수정 #21 
header, source code 수정
=> exec_cmd prototype chagne, fix init_envp

include/exec.h, include/parse.h, src/exec/exec.c, src/minishell.c, src/parse/parse.c
초기 함수 prototype, type 재정의!!
issues: #1 #6 #7
=> refactor: prototype, typedef

include/minishell_type.h
=> refactor: redefine strucre

include/minishell_type.h, include/parse.h
내부에서 작동하는 로직 변경!
issues: #6 #7
=> refactor: remove parse_args, update t_cmd

include/minishell_type.h
=> feature: update minishell structrue

lib/libft/src/memory/ft_malloc.c
ft_malloc 함수 내부 malloc -> ft_calloc으로 수정
=> feat: update ft_malloc

.vscode/launch.json, .vscode/tasks.json
=> chore: add vscode debuger setup

Makefile, include/envp.h, include/minishell.h, include/minishell_type.h, include/parse.h, include/parse_util.h, src/envp/get_envp.c, src/exit_minshell.c, src/init.c, src/minishell.c, src/parse/normalize.c, src/parse/parse_cmd.c, src/parse/print_AST.c, src/parse/tokenizer.c, src/util/get_line.c, src/util/handle_history.c, src/util/handle_key_input.c, src/util/handle_signal.c
parse_cmd, parse_arg에서 필요한 normalize 함수 추가.
tokenizer 로직 간단하게 수정
=> feat: add normalize.c

include/minishell.h, include/parse.h, include/parse_util.h, src/parse/normalize.c, src/parse/parse_cmd.c, src/parse/print_AST.c
=> feat: add parse_cmd, normalize

src/minishell.c
=> fix: ASTs memory leaks

src/util/getch.c
=> feat: add ctrl+v(paste)

include/minishell.h, src/cursor/cursor_ctrl_left.c, src/cursor/cursor_ctrl_right.c, src/util/get_line.c, src/util/getch.c, src/util/handle_key_input.c, src/util/is_util.c
ctrl + left, ctrl + right, home, end 와 같은 키 이벤트 작동 추가!
=> feat: add ctrl+arrow move, home, end key envent!

src/parse/normalize.c, src/parse/tokenizer.c
=> fix: normalize tokenizer

include/builtin.h, include/exec.h, src/builtin/export_sort.c, src/builtin/ft_export.c, src/builtin/ft_unset.c, src/envp/remove_envp.c, src/exec/exec_cmd.c, src/exec/fork.c, src/exec/free_exec.c, src/minishell.c
export sort complete && unset (env의 마지막 노드 지울때 segfault) 해결
=> export sort complete && unset (env의 마지막 노드 지울때 segfault) 해결

include/exec.h, include/minishell_type.h, src/builtin/ft_echo.c, src/builtin/ft_exit.c, src/exec/builtin_parser.c, src/exec/fork.c, src/exec/ft_cmd.c, src/exec/handle_status.c, src/util/handle_signal.c
=> feat: add signal handle
